function params = initParams()

params = struct( ...
    'auxpar',   0, ...
    'dmap',     0, ...
    'Dmedio',   0, ...
    'gamma',    0, ...
    'velmedio', 0, ...
    'wellsc',   0, ...
    'SS',       0, ...
    'h_init',   0, ...
    'MM',       0, ...
    'dt',       0, ...
    'P',        0, ...
    'theta_s',  0, ...
    'theta_r',  0, ...
    'alpha',    0, ...
    'pp',       0, ...
    'q',        0, ...
    'hs',       0, ...
    'nvg',      0 ...
);
end